### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated

### ISSUE THREAD

**Issue by labay11** [justboil/bulma-switch-control#1]
bulma-switch-control: 1.1.1
sass: 1.39.2

> [WEBPACK] DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
> [WEBPACK] 
> [WEBPACK] Recommendation: math.div($switch-width, 2)
> [WEBPACK] 
> [WEBPACK] More info and automated migrator: https://sass-lang.com/d/slash-div
> [WEBPACK] 
> [WEBPACK]    ╷
> [WEBPACK] 25 │       height: #{$switch-width / 2 + $switch-padding};
> [WEBPACK]    │                 ^^^^^^^^^^^^^^^^^
> [WEBPACK]    ╵
> [WEBPACK]     node_modules/bulma-switch-control/scss/_switch.scss 25:17        @import
> [WEBPACK]     node_modules/bulma-switch-control/bulma-switch-control.scss 3:9  @import

**Comment by labay11** [comment]
As it was done in [Bulma#3362](https://github.com/jgthms/bulma/pull/3362), it is sufficient to change the division by a multiplication. In the code, division is only used in lines 25,44 & 45 inside `_switch.scss` and can be replaced by: `#{$switch-width * 0.5 + $switch-padding};`

**Comment by labay11** [comment]
Hello @vikdiesel, why did you correctly introduced the change in efaed113147329e2b706ac37c68b5ce59126adbf but then you remove it again in cbb10554fdd66f96fcd38e8f7d04d31ecbf3fbe4?

**Comment by vikdiesel** [comment]
Sorry, there was a mistake. Now fixed.
